name: Lighthouse CI for Netlify site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Wait Netlify
        uses: denar90/wait-for-netlify-action@v2.0.2
        id: waitForNetlify
        with:
          site_id: "c8e5be00-c431-44a5-bb0d-a179e1dd72f9"
      - name: Set LHCI config
        shell: bash
        run: echo "::set-output name=file::${{github.event_name == 'pull_request' && 'lighthouserc-assertions-preview.json' || 'lighthouserc-assertions.json'}}"
        id: lhciConfig
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.waitForNetlify.outputs.url }}
            ${{ steps.waitForNetlify.outputs.url }}/about/
            ${{ steps.waitForNetlify.outputs.url }}/projects/
            ${{ steps.waitForNetlify.outputs.url }}/project/nested/lunar-eclipse
            ${{ steps.waitForNetlify.outputs.url }}/project/mars-rover
          configPath: '.github/lighthouse/${{ steps.lhciConfig.outputs.file }}'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
